services:
  - type: web
    name: rms-backend
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRY_MINUTES
        value: 480
      - key: MPESA_ENVIRONMENT
        value: sandbox
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        value: "174379"
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false
      - key: AT_USERNAME
        value: sandbox
      - key: AT_API_KEY
        sync: false
      - key: AT_SENDER_ID
        value: RMS
      - key: APP_PORT
        value: "8000"
      - key: DEBUG
        value: "False"